In [1]:
import json
import pandas as pd

# JSON 파일 불러오기
with open('라벨링데이터/TL_01. KAKAO(1)/KAKAO_898_15.json', encoding='utf-8') as f:
    data = json.load(f)

# 대화 데이터를 추출 (annotations의 lines 부분에 대화가 포함됨)
dialogue_data = data['info'][0]['annotations']['lines']

# 각 대화에서 필요한 정보를 추출하여 리스트로 저장
rows = []
for line in dialogue_data:
    rows.append({
        'id': line['id'],
        'text': line['text'],
        'speaker_id': line['speaker']['id'],
        'speaker_sex': line['speaker']['sex'],
        'speaker_age': line['speaker']['age'],
        'speech_act': line['speechAct']
    })

# 리스트를 DataFrame으로 변환
df = pd.DataFrame(rows)

# DataFrame 출력
df.head()

,id,text,speaker_id,speaker_sex,speaker_age,speech_act
0,1,1 : 이번에 캘리포니아에 산불 난 거 보셨어요?,1번,여성,30대,(지시) 질문하기
1,2,2 : 네 봤어요 ㅜㅜ 일주일 넘게 진압하고 있다는데 걱정이네요...,2번,여성,40대,(단언) 진술하기
2,3,3 : 저도 봤어요! 거기 세계에서 가장 큰 나무 있는 곳이라던데...,3번,여성,10대,(단언) 진술하기
3,4,1 : 아 제너럴 셔먼은 지금 방화담요로 둘둘 말아놨다고 하더라고요,1번,여성,30대,(단언) 진술하기
4,5,2 : 아이고... 2000~3000년 정도는 된 나무들인데 제발 빨리 진압이 되었...,2번,여성,40대,(단언) 주장하기

In [2]:
import os
import json
import pandas as pd

# 폴더 경로 설정
folder_path = '/Volumes/Extreme SSD/020.주제별 텍스트 일상 대화 데이터/01.데이터/1.Training/라벨링데이터/TL_01. KAKAO(1)'

# 파일 목록 가져오기
file_list = [file for file in os.listdir(folder_path) if file.endswith('.json')]

# 대화를 병합하여 저장할 리스트
conversation_data = []

# 각 파일을 읽어서 처리
for file_name in file_list:
    file_path = os.path.join(folder_path, file_name)
    
    # JSON 파일 열기
    with open(file_path, 'r', encoding='utf-8') as f:
        json_data = json.load(f)
        
        # 텍스트 데이터만 추출하여 하나의 문자열로 병합
        conversation = ''
        for turn in json_data:
            # 텍스트 앞에 있는 대화 번호("1 :", "2 :")를 제거하고 병합
            turn_text = turn['text']
            cleaned_text = turn_text.split(' : ', 1)[-1]  # 대화 번호 제거
            conversation += cleaned_text + ' '
        
        # 결과 저장 (파일명과 병합된 대화 텍스트)
        conversation_data.append({
            'file_name': file_name,
            'conversation': conversation.strip()  # 양끝 공백 제거
        })

# 최종 결과를 데이터프레임으로 변환
df = pd.DataFrame(conversation_data)

# 데이터프레임 저장 (필요시 경로 설정)
df.to_csv('merged_conversations.csv', index=False, encoding='utf-8')

# 데이터프레임 출력 확인
df.head()

TypeError: string indices must be integers